//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pGuestCheck" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_GuestCheck" minOccurs="0"/&gt;
 *         &lt;element name="ppMenuItemsEx" type="{http://micros-hosting.com/EGateway/}ArrayOfSimphonyPosApi_MenuItemEx" minOccurs="0"/&gt;
 *         &lt;element name="ppComboMealsEx" type="{http://micros-hosting.com/EGateway/}ArrayOfSimphonyPosApi_ComboMealEx" minOccurs="0"/&gt;
 *         &lt;element name="pSvcChargeEx" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_SvcChargeEx" minOccurs="0"/&gt;
 *         &lt;element name="pSubTotalDiscountEx" type="{http://micros-hosting.com/EGateway/}ArrayOfSimphonyPosApi_DiscountEx" minOccurs="0"/&gt;
 *         &lt;element name="pTmedDetailEx3" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_TmedDetailItemEx2" minOccurs="0"/&gt;
 *         &lt;element name="pTotalsResponseEx" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_TotalsResponseEx" minOccurs="0"/&gt;
 *         &lt;element name="ppCheckPrintLines" type="{http://micros-hosting.com/EGateway/}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="ppVoucherOutput" type="{http://micros-hosting.com/EGateway/}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="checkExtensibilityDetails" type="{http://micros-hosting.com/EGateway/}ArrayOfSimphonyPosApi_Extensibility" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pGuestCheck",
    "ppMenuItemsEx",
    "ppComboMealsEx",
    "pSvcChargeEx",
    "pSubTotalDiscountEx",
    "pTmedDetailEx3",
    "pTotalsResponseEx",
    "ppCheckPrintLines",
    "ppVoucherOutput",
    "checkExtensibilityDetails"
})
@XmlRootElement(name = "AddToExistingCheckEx2")
public class AddToExistingCheckEx2 {

    protected SimphonyPosApiGuestCheck pGuestCheck;
    protected ArrayOfSimphonyPosApiMenuItemEx ppMenuItemsEx;
    protected ArrayOfSimphonyPosApiComboMealEx ppComboMealsEx;
    protected SimphonyPosApiSvcChargeEx pSvcChargeEx;
    protected ArrayOfSimphonyPosApiDiscountEx pSubTotalDiscountEx;
    protected SimphonyPosApiTmedDetailItemEx2 pTmedDetailEx3;
    protected SimphonyPosApiTotalsResponseEx pTotalsResponseEx;
    protected ArrayOfString ppCheckPrintLines;
    protected ArrayOfString ppVoucherOutput;
    protected ArrayOfSimphonyPosApiExtensibility checkExtensibilityDetails;

    /**
     * Gets the value of the pGuestCheck property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiGuestCheck }
     *     
     */
    public SimphonyPosApiGuestCheck getPGuestCheck() {
        return pGuestCheck;
    }

    /**
     * Sets the value of the pGuestCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiGuestCheck }
     *     
     */
    public void setPGuestCheck(SimphonyPosApiGuestCheck value) {
        this.pGuestCheck = value;
    }

    /**
     * Gets the value of the ppMenuItemsEx property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSimphonyPosApiMenuItemEx }
     *     
     */
    public ArrayOfSimphonyPosApiMenuItemEx getPpMenuItemsEx() {
        return ppMenuItemsEx;
    }

    /**
     * Sets the value of the ppMenuItemsEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSimphonyPosApiMenuItemEx }
     *     
     */
    public void setPpMenuItemsEx(ArrayOfSimphonyPosApiMenuItemEx value) {
        this.ppMenuItemsEx = value;
    }

    /**
     * Gets the value of the ppComboMealsEx property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSimphonyPosApiComboMealEx }
     *     
     */
    public ArrayOfSimphonyPosApiComboMealEx getPpComboMealsEx() {
        return ppComboMealsEx;
    }

    /**
     * Sets the value of the ppComboMealsEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSimphonyPosApiComboMealEx }
     *     
     */
    public void setPpComboMealsEx(ArrayOfSimphonyPosApiComboMealEx value) {
        this.ppComboMealsEx = value;
    }

    /**
     * Gets the value of the pSvcChargeEx property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiSvcChargeEx }
     *     
     */
    public SimphonyPosApiSvcChargeEx getPSvcChargeEx() {
        return pSvcChargeEx;
    }

    /**
     * Sets the value of the pSvcChargeEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiSvcChargeEx }
     *     
     */
    public void setPSvcChargeEx(SimphonyPosApiSvcChargeEx value) {
        this.pSvcChargeEx = value;
    }

    /**
     * Gets the value of the pSubTotalDiscountEx property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSimphonyPosApiDiscountEx }
     *     
     */
    public ArrayOfSimphonyPosApiDiscountEx getPSubTotalDiscountEx() {
        return pSubTotalDiscountEx;
    }

    /**
     * Sets the value of the pSubTotalDiscountEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSimphonyPosApiDiscountEx }
     *     
     */
    public void setPSubTotalDiscountEx(ArrayOfSimphonyPosApiDiscountEx value) {
        this.pSubTotalDiscountEx = value;
    }

    /**
     * Gets the value of the pTmedDetailEx3 property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiTmedDetailItemEx2 }
     *     
     */
    public SimphonyPosApiTmedDetailItemEx2 getPTmedDetailEx3() {
        return pTmedDetailEx3;
    }

    /**
     * Sets the value of the pTmedDetailEx3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiTmedDetailItemEx2 }
     *     
     */
    public void setPTmedDetailEx3(SimphonyPosApiTmedDetailItemEx2 value) {
        this.pTmedDetailEx3 = value;
    }

    /**
     * Gets the value of the pTotalsResponseEx property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiTotalsResponseEx }
     *     
     */
    public SimphonyPosApiTotalsResponseEx getPTotalsResponseEx() {
        return pTotalsResponseEx;
    }

    /**
     * Sets the value of the pTotalsResponseEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiTotalsResponseEx }
     *     
     */
    public void setPTotalsResponseEx(SimphonyPosApiTotalsResponseEx value) {
        this.pTotalsResponseEx = value;
    }

    /**
     * Gets the value of the ppCheckPrintLines property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getPpCheckPrintLines() {
        return ppCheckPrintLines;
    }

    /**
     * Sets the value of the ppCheckPrintLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setPpCheckPrintLines(ArrayOfString value) {
        this.ppCheckPrintLines = value;
    }

    /**
     * Gets the value of the ppVoucherOutput property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getPpVoucherOutput() {
        return ppVoucherOutput;
    }

    /**
     * Sets the value of the ppVoucherOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setPpVoucherOutput(ArrayOfString value) {
        this.ppVoucherOutput = value;
    }

    /**
     * Gets the value of the checkExtensibilityDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSimphonyPosApiExtensibility }
     *     
     */
    public ArrayOfSimphonyPosApiExtensibility getCheckExtensibilityDetails() {
        return checkExtensibilityDetails;
    }

    /**
     * Sets the value of the checkExtensibilityDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSimphonyPosApiExtensibility }
     *     
     */
    public void setCheckExtensibilityDetails(ArrayOfSimphonyPosApiExtensibility value) {
        this.checkExtensibilityDetails = value;
    }

}
