//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vendorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pGuestCheck" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_GuestCheck" minOccurs="0"/&gt;
 *         &lt;element name="ppMenuItems" type="{http://micros-hosting.com/EGateway/}ArrayOfSimphonyPosApi_MenuItem" minOccurs="0"/&gt;
 *         &lt;element name="ppComboMeals" type="{http://micros-hosting.com/EGateway/}ArrayOfSimphonyPosApi_ComboMeal" minOccurs="0"/&gt;
 *         &lt;element name="pServiceChg" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_SvcCharge" minOccurs="0"/&gt;
 *         &lt;element name="pSubTotalDiscount" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_Discount" minOccurs="0"/&gt;
 *         &lt;element name="pTmedDetail" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_TmedDetailItemEx" minOccurs="0"/&gt;
 *         &lt;element name="pTotalsResponse" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_TotalsResponse" minOccurs="0"/&gt;
 *         &lt;element name="ppCheckPrintLines" type="{http://micros-hosting.com/EGateway/}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="ppVoucherOutput" type="{http://micros-hosting.com/EGateway/}ArrayOfString" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vendorCode",
    "pGuestCheck",
    "ppMenuItems",
    "ppComboMeals",
    "pServiceChg",
    "pSubTotalDiscount",
    "pTmedDetail",
    "pTotalsResponse",
    "ppCheckPrintLines",
    "ppVoucherOutput"
})
@XmlRootElement(name = "AddToExistingCheckEx")
public class AddToExistingCheckEx {

    protected String vendorCode;
    protected SimphonyPosApiGuestCheck pGuestCheck;
    protected ArrayOfSimphonyPosApiMenuItem ppMenuItems;
    protected ArrayOfSimphonyPosApiComboMeal ppComboMeals;
    protected SimphonyPosApiSvcCharge pServiceChg;
    protected SimphonyPosApiDiscount pSubTotalDiscount;
    protected SimphonyPosApiTmedDetailItemEx pTmedDetail;
    protected SimphonyPosApiTotalsResponse pTotalsResponse;
    protected ArrayOfString ppCheckPrintLines;
    protected ArrayOfString ppVoucherOutput;

    /**
     * Gets the value of the vendorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorCode() {
        return vendorCode;
    }

    /**
     * Sets the value of the vendorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorCode(String value) {
        this.vendorCode = value;
    }

    /**
     * Gets the value of the pGuestCheck property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiGuestCheck }
     *     
     */
    public SimphonyPosApiGuestCheck getPGuestCheck() {
        return pGuestCheck;
    }

    /**
     * Sets the value of the pGuestCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiGuestCheck }
     *     
     */
    public void setPGuestCheck(SimphonyPosApiGuestCheck value) {
        this.pGuestCheck = value;
    }

    /**
     * Gets the value of the ppMenuItems property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSimphonyPosApiMenuItem }
     *     
     */
    public ArrayOfSimphonyPosApiMenuItem getPpMenuItems() {
        return ppMenuItems;
    }

    /**
     * Sets the value of the ppMenuItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSimphonyPosApiMenuItem }
     *     
     */
    public void setPpMenuItems(ArrayOfSimphonyPosApiMenuItem value) {
        this.ppMenuItems = value;
    }

    /**
     * Gets the value of the ppComboMeals property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSimphonyPosApiComboMeal }
     *     
     */
    public ArrayOfSimphonyPosApiComboMeal getPpComboMeals() {
        return ppComboMeals;
    }

    /**
     * Sets the value of the ppComboMeals property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSimphonyPosApiComboMeal }
     *     
     */
    public void setPpComboMeals(ArrayOfSimphonyPosApiComboMeal value) {
        this.ppComboMeals = value;
    }

    /**
     * Gets the value of the pServiceChg property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiSvcCharge }
     *     
     */
    public SimphonyPosApiSvcCharge getPServiceChg() {
        return pServiceChg;
    }

    /**
     * Sets the value of the pServiceChg property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiSvcCharge }
     *     
     */
    public void setPServiceChg(SimphonyPosApiSvcCharge value) {
        this.pServiceChg = value;
    }

    /**
     * Gets the value of the pSubTotalDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiDiscount }
     *     
     */
    public SimphonyPosApiDiscount getPSubTotalDiscount() {
        return pSubTotalDiscount;
    }

    /**
     * Sets the value of the pSubTotalDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiDiscount }
     *     
     */
    public void setPSubTotalDiscount(SimphonyPosApiDiscount value) {
        this.pSubTotalDiscount = value;
    }

    /**
     * Gets the value of the pTmedDetail property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiTmedDetailItemEx }
     *     
     */
    public SimphonyPosApiTmedDetailItemEx getPTmedDetail() {
        return pTmedDetail;
    }

    /**
     * Sets the value of the pTmedDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiTmedDetailItemEx }
     *     
     */
    public void setPTmedDetail(SimphonyPosApiTmedDetailItemEx value) {
        this.pTmedDetail = value;
    }

    /**
     * Gets the value of the pTotalsResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiTotalsResponse }
     *     
     */
    public SimphonyPosApiTotalsResponse getPTotalsResponse() {
        return pTotalsResponse;
    }

    /**
     * Sets the value of the pTotalsResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiTotalsResponse }
     *     
     */
    public void setPTotalsResponse(SimphonyPosApiTotalsResponse value) {
        this.pTotalsResponse = value;
    }

    /**
     * Gets the value of the ppCheckPrintLines property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getPpCheckPrintLines() {
        return ppCheckPrintLines;
    }

    /**
     * Sets the value of the ppCheckPrintLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setPpCheckPrintLines(ArrayOfString value) {
        this.ppCheckPrintLines = value;
    }

    /**
     * Gets the value of the ppVoucherOutput property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getPpVoucherOutput() {
        return ppVoucherOutput;
    }

    /**
     * Sets the value of the ppVoucherOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setPpVoucherOutput(ArrayOfString value) {
        this.ppVoucherOutput = value;
    }

}
