//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfSimphonyPosApi_TmedDetailItemEx2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfSimphonyPosApi_TmedDetailItemEx2"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SimphonyPosApi_TmedDetailItemEx2" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_TmedDetailItemEx2" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfSimphonyPosApi_TmedDetailItemEx2", propOrder = {
    "simphonyPosApiTmedDetailItemEx2"
})
public class ArrayOfSimphonyPosApiTmedDetailItemEx2 {

    @XmlElement(name = "SimphonyPosApi_TmedDetailItemEx2", nillable = true)
    protected List<SimphonyPosApiTmedDetailItemEx2> simphonyPosApiTmedDetailItemEx2;

    /**
     * Gets the value of the simphonyPosApiTmedDetailItemEx2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simphonyPosApiTmedDetailItemEx2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimphonyPosApiTmedDetailItemEx2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimphonyPosApiTmedDetailItemEx2 }
     * 
     * 
     */
    public List<SimphonyPosApiTmedDetailItemEx2> getSimphonyPosApiTmedDetailItemEx2() {
        if (simphonyPosApiTmedDetailItemEx2 == null) {
            simphonyPosApiTmedDetailItemEx2 = new ArrayList<SimphonyPosApiTmedDetailItemEx2>();
        }
        return this.simphonyPosApiTmedDetailItemEx2;
    }

}
