//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vendorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ppMenuItems" type="{http://micros-hosting.com/EGateway/}ArrayOfSimphonyPosApi_MenuItem" minOccurs="0"/&gt;
 *         &lt;element name="ppComboMeals" type="{http://micros-hosting.com/EGateway/}ArrayOfSimphonyPosApi_ComboMeal" minOccurs="0"/&gt;
 *         &lt;element name="pSvcCharge" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_SvcCharge" minOccurs="0"/&gt;
 *         &lt;element name="pSubtotalDiscount" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_Discount" minOccurs="0"/&gt;
 *         &lt;element name="revenueCenter" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="orderType" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="employeeNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="pTotalsResponse" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_TotalsResponse" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vendorCode",
    "ppMenuItems",
    "ppComboMeals",
    "pSvcCharge",
    "pSubtotalDiscount",
    "revenueCenter",
    "orderType",
    "employeeNumber",
    "pTotalsResponse"
})
@XmlRootElement(name = "CalculateTransactionTotals")
public class CalculateTransactionTotals {

    protected String vendorCode;
    protected ArrayOfSimphonyPosApiMenuItem ppMenuItems;
    protected ArrayOfSimphonyPosApiComboMeal ppComboMeals;
    protected SimphonyPosApiSvcCharge pSvcCharge;
    protected SimphonyPosApiDiscount pSubtotalDiscount;
    protected int revenueCenter;
    protected short orderType;
    protected int employeeNumber;
    protected SimphonyPosApiTotalsResponse pTotalsResponse;

    /**
     * Gets the value of the vendorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorCode() {
        return vendorCode;
    }

    /**
     * Sets the value of the vendorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorCode(String value) {
        this.vendorCode = value;
    }

    /**
     * Gets the value of the ppMenuItems property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSimphonyPosApiMenuItem }
     *     
     */
    public ArrayOfSimphonyPosApiMenuItem getPpMenuItems() {
        return ppMenuItems;
    }

    /**
     * Sets the value of the ppMenuItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSimphonyPosApiMenuItem }
     *     
     */
    public void setPpMenuItems(ArrayOfSimphonyPosApiMenuItem value) {
        this.ppMenuItems = value;
    }

    /**
     * Gets the value of the ppComboMeals property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSimphonyPosApiComboMeal }
     *     
     */
    public ArrayOfSimphonyPosApiComboMeal getPpComboMeals() {
        return ppComboMeals;
    }

    /**
     * Sets the value of the ppComboMeals property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSimphonyPosApiComboMeal }
     *     
     */
    public void setPpComboMeals(ArrayOfSimphonyPosApiComboMeal value) {
        this.ppComboMeals = value;
    }

    /**
     * Gets the value of the pSvcCharge property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiSvcCharge }
     *     
     */
    public SimphonyPosApiSvcCharge getPSvcCharge() {
        return pSvcCharge;
    }

    /**
     * Sets the value of the pSvcCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiSvcCharge }
     *     
     */
    public void setPSvcCharge(SimphonyPosApiSvcCharge value) {
        this.pSvcCharge = value;
    }

    /**
     * Gets the value of the pSubtotalDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiDiscount }
     *     
     */
    public SimphonyPosApiDiscount getPSubtotalDiscount() {
        return pSubtotalDiscount;
    }

    /**
     * Sets the value of the pSubtotalDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiDiscount }
     *     
     */
    public void setPSubtotalDiscount(SimphonyPosApiDiscount value) {
        this.pSubtotalDiscount = value;
    }

    /**
     * Gets the value of the revenueCenter property.
     * 
     */
    public int getRevenueCenter() {
        return revenueCenter;
    }

    /**
     * Sets the value of the revenueCenter property.
     * 
     */
    public void setRevenueCenter(int value) {
        this.revenueCenter = value;
    }

    /**
     * Gets the value of the orderType property.
     * 
     */
    public short getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     */
    public void setOrderType(short value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the employeeNumber property.
     * 
     */
    public int getEmployeeNumber() {
        return employeeNumber;
    }

    /**
     * Sets the value of the employeeNumber property.
     * 
     */
    public void setEmployeeNumber(int value) {
        this.employeeNumber = value;
    }

    /**
     * Gets the value of the pTotalsResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiTotalsResponse }
     *     
     */
    public SimphonyPosApiTotalsResponse getPTotalsResponse() {
        return pTotalsResponse;
    }

    /**
     * Sets the value of the pTotalsResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiTotalsResponse }
     *     
     */
    public void setPTotalsResponse(SimphonyPosApiTotalsResponse value) {
        this.pTotalsResponse = value;
    }

}
