//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ppMenuItemsEx" type="{http://micros-hosting.com/EGateway/}ArrayOfSimphonyPosApi_MenuItemEx" minOccurs="0"/&gt;
 *         &lt;element name="ppComboMealsEx" type="{http://micros-hosting.com/EGateway/}ArrayOfSimphonyPosApi_ComboMealEx" minOccurs="0"/&gt;
 *         &lt;element name="pSvcChargeEx" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_SvcChargeEx" minOccurs="0"/&gt;
 *         &lt;element name="pSubTotalDiscountEx" type="{http://micros-hosting.com/EGateway/}ArrayOfSimphonyPosApi_DiscountEx" minOccurs="0"/&gt;
 *         &lt;element name="revenueCenterObjectNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="orderType" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="employeeObjectNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="checkGuestcount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="pTotalsResponseEx" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_TotalsResponseEx" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ppMenuItemsEx",
    "ppComboMealsEx",
    "pSvcChargeEx",
    "pSubTotalDiscountEx",
    "revenueCenterObjectNum",
    "orderType",
    "employeeObjectNum",
    "checkGuestcount",
    "pTotalsResponseEx"
})
@XmlRootElement(name = "CalculateTransactionTotalsEx")
public class CalculateTransactionTotalsEx {

    protected ArrayOfSimphonyPosApiMenuItemEx ppMenuItemsEx;
    protected ArrayOfSimphonyPosApiComboMealEx ppComboMealsEx;
    protected SimphonyPosApiSvcChargeEx pSvcChargeEx;
    protected ArrayOfSimphonyPosApiDiscountEx pSubTotalDiscountEx;
    protected int revenueCenterObjectNum;
    protected short orderType;
    protected int employeeObjectNum;
    protected int checkGuestcount;
    protected SimphonyPosApiTotalsResponseEx pTotalsResponseEx;

    /**
     * Gets the value of the ppMenuItemsEx property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSimphonyPosApiMenuItemEx }
     *     
     */
    public ArrayOfSimphonyPosApiMenuItemEx getPpMenuItemsEx() {
        return ppMenuItemsEx;
    }

    /**
     * Sets the value of the ppMenuItemsEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSimphonyPosApiMenuItemEx }
     *     
     */
    public void setPpMenuItemsEx(ArrayOfSimphonyPosApiMenuItemEx value) {
        this.ppMenuItemsEx = value;
    }

    /**
     * Gets the value of the ppComboMealsEx property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSimphonyPosApiComboMealEx }
     *     
     */
    public ArrayOfSimphonyPosApiComboMealEx getPpComboMealsEx() {
        return ppComboMealsEx;
    }

    /**
     * Sets the value of the ppComboMealsEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSimphonyPosApiComboMealEx }
     *     
     */
    public void setPpComboMealsEx(ArrayOfSimphonyPosApiComboMealEx value) {
        this.ppComboMealsEx = value;
    }

    /**
     * Gets the value of the pSvcChargeEx property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiSvcChargeEx }
     *     
     */
    public SimphonyPosApiSvcChargeEx getPSvcChargeEx() {
        return pSvcChargeEx;
    }

    /**
     * Sets the value of the pSvcChargeEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiSvcChargeEx }
     *     
     */
    public void setPSvcChargeEx(SimphonyPosApiSvcChargeEx value) {
        this.pSvcChargeEx = value;
    }

    /**
     * Gets the value of the pSubTotalDiscountEx property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSimphonyPosApiDiscountEx }
     *     
     */
    public ArrayOfSimphonyPosApiDiscountEx getPSubTotalDiscountEx() {
        return pSubTotalDiscountEx;
    }

    /**
     * Sets the value of the pSubTotalDiscountEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSimphonyPosApiDiscountEx }
     *     
     */
    public void setPSubTotalDiscountEx(ArrayOfSimphonyPosApiDiscountEx value) {
        this.pSubTotalDiscountEx = value;
    }

    /**
     * Gets the value of the revenueCenterObjectNum property.
     * 
     */
    public int getRevenueCenterObjectNum() {
        return revenueCenterObjectNum;
    }

    /**
     * Sets the value of the revenueCenterObjectNum property.
     * 
     */
    public void setRevenueCenterObjectNum(int value) {
        this.revenueCenterObjectNum = value;
    }

    /**
     * Gets the value of the orderType property.
     * 
     */
    public short getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     */
    public void setOrderType(short value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the employeeObjectNum property.
     * 
     */
    public int getEmployeeObjectNum() {
        return employeeObjectNum;
    }

    /**
     * Sets the value of the employeeObjectNum property.
     * 
     */
    public void setEmployeeObjectNum(int value) {
        this.employeeObjectNum = value;
    }

    /**
     * Gets the value of the checkGuestcount property.
     * 
     */
    public int getCheckGuestcount() {
        return checkGuestcount;
    }

    /**
     * Sets the value of the checkGuestcount property.
     * 
     */
    public void setCheckGuestcount(int value) {
        this.checkGuestcount = value;
    }

    /**
     * Gets the value of the pTotalsResponseEx property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiTotalsResponseEx }
     *     
     */
    public SimphonyPosApiTotalsResponseEx getPTotalsResponseEx() {
        return pTotalsResponseEx;
    }

    /**
     * Sets the value of the pTotalsResponseEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiTotalsResponseEx }
     *     
     */
    public void setPTotalsResponseEx(SimphonyPosApiTotalsResponseEx value) {
        this.pTotalsResponseEx = value;
    }

}
