//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EAccountDataSource.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EAccountDataSource"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SOURCE_UNDEFINED"/&gt;
 *     &lt;enumeration value="MAGNETIC_STRIPE"/&gt;
 *     &lt;enumeration value="RFID_TRACK_DATA_RULES"/&gt;
 *     &lt;enumeration value="RFID_M_CHIP_RULES"/&gt;
 *     &lt;enumeration value="MANUALLY_KEYED_TRACK_1_CAPABLE"/&gt;
 *     &lt;enumeration value="MANUALLY_KEYED_TRACK_2_CAPABLE"/&gt;
 *     &lt;enumeration value="MANUALLY_KEYED_NO_CARD_READER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EAccountDataSource")
@XmlEnum
public enum EAccountDataSource {

    SOURCE_UNDEFINED,
    MAGNETIC_STRIPE,
    RFID_TRACK_DATA_RULES,
    RFID_M_CHIP_RULES,
    MANUALLY_KEYED_TRACK_1_CAPABLE,
    MANUALLY_KEYED_TRACK_2_CAPABLE,
    MANUALLY_KEYED_NO_CARD_READER;

    public String value() {
        return name();
    }

    public static EAccountDataSource fromValue(String v) {
        return valueOf(v);
    }

}
