//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EConfigurationInfoType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EConfigurationInfoType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNDEFINED"/&gt;
 *     &lt;enumeration value="MENUITEMDEFINITIONS"/&gt;
 *     &lt;enumeration value="MENUITEMPRICE"/&gt;
 *     &lt;enumeration value="MENUITEMCLASS"/&gt;
 *     &lt;enumeration value="SERVICECHARGE"/&gt;
 *     &lt;enumeration value="DISCOUNTDEFINITIONS"/&gt;
 *     &lt;enumeration value="TENDERMEDIA"/&gt;
 *     &lt;enumeration value="ORDERTYPE"/&gt;
 *     &lt;enumeration value="FAMILYGROUP"/&gt;
 *     &lt;enumeration value="MAJORGROUP"/&gt;
 *     &lt;enumeration value="REVENUECENTERPARAMETER"/&gt;
 *     &lt;enumeration value="REVENUECENTERS"/&gt;
 *     &lt;enumeration value="INTERFACES"/&gt;
 *     &lt;enumeration value="MENUITEMMASTERS"/&gt;
 *     &lt;enumeration value="SERVINGPERIODS"/&gt;
 *     &lt;enumeration value="CURRENCY"/&gt;
 *     &lt;enumeration value="VERSION"/&gt;
 *     &lt;enumeration value="EMPLOYEES"/&gt;
 *     &lt;enumeration value="TABLES"/&gt;
 *     &lt;enumeration value="LANGUAGEINFORMATION"/&gt;
 *     &lt;enumeration value="MENULEVEL"/&gt;
 *     &lt;enumeration value="MENUITEMSLU"/&gt;
 *     &lt;enumeration value="MAINMENULEVEL"/&gt;
 *     &lt;enumeration value="SUBMENULEVEL"/&gt;
 *     &lt;enumeration value="EVENTTYPES"/&gt;
 *     &lt;enumeration value="EVENTSUBTYPES"/&gt;
 *     &lt;enumeration value="EVENTDEFINITIONS"/&gt;
 *     &lt;enumeration value="TAX"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EConfigurationInfoType")
@XmlEnum
public enum EConfigurationInfoType {

    UNDEFINED,
    MENUITEMDEFINITIONS,
    MENUITEMPRICE,
    MENUITEMCLASS,
    SERVICECHARGE,
    DISCOUNTDEFINITIONS,
    TENDERMEDIA,
    ORDERTYPE,
    FAMILYGROUP,
    MAJORGROUP,
    REVENUECENTERPARAMETER,
    REVENUECENTERS,
    INTERFACES,
    MENUITEMMASTERS,
    SERVINGPERIODS,
    CURRENCY,
    VERSION,
    EMPLOYEES,
    TABLES,
    LANGUAGEINFORMATION,
    MENULEVEL,
    MENUITEMSLU,
    MAINMENULEVEL,
    SUBMENULEVEL,
    EVENTTYPES,
    EVENTSUBTYPES,
    EVENTDEFINITIONS,
    TAX;

    public String value() {
        return name();
    }

    public static EConfigurationInfoType fromValue(String v) {
        return valueOf(v);
    }

}
