//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EPaymentDirective.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EPaymentDirective"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NO_E_PAYMENT"/&gt;
 *     &lt;enumeration value="CREDIT_AUTHORIZE_ONLY"/&gt;
 *     &lt;enumeration value="CREDIT_AUTHORIZE_AND_PAY"/&gt;
 *     &lt;enumeration value="DEBIT_AUTHORIZE_ONLY"/&gt;
 *     &lt;enumeration value="DEBIT_AUTHORIZE_AND_PAY"/&gt;
 *     &lt;enumeration value="STORED_VALUE_CARD_AUTHORIZE"/&gt;
 *     &lt;enumeration value="STORED_VALUE_CARD_REDEEM"/&gt;
 *     &lt;enumeration value="GET_DEBIT_CANCEL_VOUCHER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EPaymentDirective")
@XmlEnum
public enum EPaymentDirective {

    NO_E_PAYMENT,
    CREDIT_AUTHORIZE_ONLY,
    CREDIT_AUTHORIZE_AND_PAY,
    DEBIT_AUTHORIZE_ONLY,
    DEBIT_AUTHORIZE_AND_PAY,
    STORED_VALUE_CARD_AUTHORIZE,
    STORED_VALUE_CARD_REDEEM,
    GET_DEBIT_CANCEL_VOUCHER;

    public String value() {
        return name();
    }

    public static EPaymentDirective fromValue(String v) {
        return valueOf(v);
    }

}
