//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="configInfoRequest" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_ConfigInfoRequest" minOccurs="0"/&gt;
 *         &lt;element name="configInfoResponse" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_ConfigInfoResponse" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "configInfoRequest",
    "configInfoResponse"
})
@XmlRootElement(name = "GetConfigurationInfoEx")
public class GetConfigurationInfoEx {

    protected SimphonyPosApiConfigInfoRequest configInfoRequest;
    protected SimphonyPosApiConfigInfoResponse configInfoResponse;

    /**
     * Gets the value of the configInfoRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiConfigInfoRequest }
     *     
     */
    public SimphonyPosApiConfigInfoRequest getConfigInfoRequest() {
        return configInfoRequest;
    }

    /**
     * Sets the value of the configInfoRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiConfigInfoRequest }
     *     
     */
    public void setConfigInfoRequest(SimphonyPosApiConfigInfoRequest value) {
        this.configInfoRequest = value;
    }

    /**
     * Gets the value of the configInfoResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiConfigInfoResponse }
     *     
     */
    public SimphonyPosApiConfigInfoResponse getConfigInfoResponse() {
        return configInfoResponse;
    }

    /**
     * Sets the value of the configInfoResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiConfigInfoResponse }
     *     
     */
    public void setConfigInfoResponse(SimphonyPosApiConfigInfoResponse value) {
        this.configInfoResponse = value;
    }

}
