//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="vendorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="employeeObjectNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="configurationInfoType" type="{http://micros-hosting.com/EGateway/}ArrayOfInt" minOccurs="0"/&gt;
 *         &lt;element name="revenueCenter" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="configInfoResponse" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_ConfigInfoResponse" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vendorCode",
    "employeeObjectNum",
    "configurationInfoType",
    "revenueCenter",
    "configInfoResponse"
})
@XmlRootElement(name = "GetConfigurationInfo")
public class GetConfigurationInfo {

    protected String vendorCode;
    protected int employeeObjectNum;
    protected ArrayOfInt configurationInfoType;
    protected int revenueCenter;
    protected SimphonyPosApiConfigInfoResponse configInfoResponse;

    /**
     * Gets the value of the vendorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorCode() {
        return vendorCode;
    }

    /**
     * Sets the value of the vendorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorCode(String value) {
        this.vendorCode = value;
    }

    /**
     * Gets the value of the employeeObjectNum property.
     * 
     */
    public int getEmployeeObjectNum() {
        return employeeObjectNum;
    }

    /**
     * Sets the value of the employeeObjectNum property.
     * 
     */
    public void setEmployeeObjectNum(int value) {
        this.employeeObjectNum = value;
    }

    /**
     * Gets the value of the configurationInfoType property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfInt }
     *     
     */
    public ArrayOfInt getConfigurationInfoType() {
        return configurationInfoType;
    }

    /**
     * Sets the value of the configurationInfoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfInt }
     *     
     */
    public void setConfigurationInfoType(ArrayOfInt value) {
        this.configurationInfoType = value;
    }

    /**
     * Gets the value of the revenueCenter property.
     * 
     */
    public int getRevenueCenter() {
        return revenueCenter;
    }

    /**
     * Sets the value of the revenueCenter property.
     * 
     */
    public void setRevenueCenter(int value) {
        this.revenueCenter = value;
    }

    /**
     * Gets the value of the configInfoResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiConfigInfoResponse }
     *     
     */
    public SimphonyPosApiConfigInfoResponse getConfigInfoResponse() {
        return configInfoResponse;
    }

    /**
     * Sets the value of the configInfoResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiConfigInfoResponse }
     *     
     */
    public void setConfigInfoResponse(SimphonyPosApiConfigInfoResponse value) {
        this.configInfoResponse = value;
    }

}
