//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ppCheckDetailFilter" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_CheckDetailRequest" minOccurs="0"/&gt;
 *         &lt;element name="ppCheckDetailResponse" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_CheckDetailResponse" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ppCheckDetailFilter",
    "ppCheckDetailResponse"
})
@XmlRootElement(name = "GetCheckDetail")
public class GetCheckDetail {

    protected SimphonyPosApiCheckDetailRequest ppCheckDetailFilter;
    protected SimphonyPosApiCheckDetailResponse ppCheckDetailResponse;

    /**
     * Gets the value of the ppCheckDetailFilter property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiCheckDetailRequest }
     *     
     */
    public SimphonyPosApiCheckDetailRequest getPpCheckDetailFilter() {
        return ppCheckDetailFilter;
    }

    /**
     * Sets the value of the ppCheckDetailFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiCheckDetailRequest }
     *     
     */
    public void setPpCheckDetailFilter(SimphonyPosApiCheckDetailRequest value) {
        this.ppCheckDetailFilter = value;
    }

    /**
     * Gets the value of the ppCheckDetailResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiCheckDetailResponse }
     *     
     */
    public SimphonyPosApiCheckDetailResponse getPpCheckDetailResponse() {
        return ppCheckDetailResponse;
    }

    /**
     * Sets the value of the ppCheckDetailResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiCheckDetailResponse }
     *     
     */
    public void setPpCheckDetailResponse(SimphonyPosApiCheckDetailResponse value) {
        this.ppCheckDetailResponse = value;
    }

}
