//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.simphony.pos.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.simphony.pos.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CalculateTransactionTotals }
     * 
     */
    public CalculateTransactionTotals createCalculateTransactionTotals() {
        return new CalculateTransactionTotals();
    }

    /**
     * Create an instance of {@link ArrayOfSimphonyPosApiMenuItem }
     * 
     */
    public ArrayOfSimphonyPosApiMenuItem createArrayOfSimphonyPosApiMenuItem() {
        return new ArrayOfSimphonyPosApiMenuItem();
    }

    /**
     * Create an instance of {@link ArrayOfSimphonyPosApiComboMeal }
     * 
     */
    public ArrayOfSimphonyPosApiComboMeal createArrayOfSimphonyPosApiComboMeal() {
        return new ArrayOfSimphonyPosApiComboMeal();
    }

    /**
     * Create an instance of {@link SimphonyPosApiSvcCharge }
     * 
     */
    public SimphonyPosApiSvcCharge createSimphonyPosApiSvcCharge() {
        return new SimphonyPosApiSvcCharge();
    }

    /**
     * Create an instance of {@link SimphonyPosApiDiscount }
     * 
     */
    public SimphonyPosApiDiscount createSimphonyPosApiDiscount() {
        return new SimphonyPosApiDiscount();
    }

    /**
     * Create an instance of {@link SimphonyPosApiTotalsResponse }
     * 
     */
    public SimphonyPosApiTotalsResponse createSimphonyPosApiTotalsResponse() {
        return new SimphonyPosApiTotalsResponse();
    }

    /**
     * Create an instance of {@link CalculateTransactionTotalsResponse }
     * 
     */
    public CalculateTransactionTotalsResponse createCalculateTransactionTotalsResponse() {
        return new CalculateTransactionTotalsResponse();
    }

    /**
     * Create an instance of {@link GetConfigurationInfo }
     * 
     */
    public GetConfigurationInfo createGetConfigurationInfo() {
        return new GetConfigurationInfo();
    }

    /**
     * Create an instance of {@link ArrayOfInt }
     * 
     */
    public ArrayOfInt createArrayOfInt() {
        return new ArrayOfInt();
    }

    /**
     * Create an instance of {@link SimphonyPosApiConfigInfoResponse }
     * 
     */
    public SimphonyPosApiConfigInfoResponse createSimphonyPosApiConfigInfoResponse() {
        return new SimphonyPosApiConfigInfoResponse();
    }

    /**
     * Create an instance of {@link GetConfigurationInfoResponse }
     * 
     */
    public GetConfigurationInfoResponse createGetConfigurationInfoResponse() {
        return new GetConfigurationInfoResponse();
    }

    /**
     * Create an instance of {@link GetConfigurationInfoEx }
     * 
     */
    public GetConfigurationInfoEx createGetConfigurationInfoEx() {
        return new GetConfigurationInfoEx();
    }

    /**
     * Create an instance of {@link SimphonyPosApiConfigInfoRequest }
     * 
     */
    public SimphonyPosApiConfigInfoRequest createSimphonyPosApiConfigInfoRequest() {
        return new SimphonyPosApiConfigInfoRequest();
    }

    /**
     * Create an instance of {@link GetConfigurationInfoExResponse }
     * 
     */
    public GetConfigurationInfoExResponse createGetConfigurationInfoExResponse() {
        return new GetConfigurationInfoExResponse();
    }

    /**
     * Create an instance of {@link PostTransactionEx }
     * 
     */
    public PostTransactionEx createPostTransactionEx() {
        return new PostTransactionEx();
    }

    /**
     * Create an instance of {@link SimphonyPosApiGuestCheck }
     * 
     */
    public SimphonyPosApiGuestCheck createSimphonyPosApiGuestCheck() {
        return new SimphonyPosApiGuestCheck();
    }

    /**
     * Create an instance of {@link SimphonyPosApiTmedDetailItemEx }
     * 
     */
    public SimphonyPosApiTmedDetailItemEx createSimphonyPosApiTmedDetailItemEx() {
        return new SimphonyPosApiTmedDetailItemEx();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link PostTransactionExResponse }
     * 
     */
    public PostTransactionExResponse createPostTransactionExResponse() {
        return new PostTransactionExResponse();
    }

    /**
     * Create an instance of {@link AddToExistingCheckEx }
     * 
     */
    public AddToExistingCheckEx createAddToExistingCheckEx() {
        return new AddToExistingCheckEx();
    }

    /**
     * Create an instance of {@link AddToExistingCheckExResponse }
     * 
     */
    public AddToExistingCheckExResponse createAddToExistingCheckExResponse() {
        return new AddToExistingCheckExResponse();
    }

    /**
     * Create an instance of {@link VoidTransaction }
     * 
     */
    public VoidTransaction createVoidTransaction() {
        return new VoidTransaction();
    }

    /**
     * Create an instance of {@link VoidTransactionResponse }
     * 
     */
    public VoidTransactionResponse createVoidTransactionResponse() {
        return new VoidTransactionResponse();
    }

    /**
     * Create an instance of {@link CheckPrintJobStatus }
     * 
     */
    public CheckPrintJobStatus createCheckPrintJobStatus() {
        return new CheckPrintJobStatus();
    }

    /**
     * Create an instance of {@link SimphonyPrintApiPrintJobStatus }
     * 
     */
    public SimphonyPrintApiPrintJobStatus createSimphonyPrintApiPrintJobStatus() {
        return new SimphonyPrintApiPrintJobStatus();
    }

    /**
     * Create an instance of {@link CheckPrintJobStatusResponse }
     * 
     */
    public CheckPrintJobStatusResponse createCheckPrintJobStatusResponse() {
        return new CheckPrintJobStatusResponse();
    }

    /**
     * Create an instance of {@link GetPrintedCheck }
     * 
     */
    public GetPrintedCheck createGetPrintedCheck() {
        return new GetPrintedCheck();
    }

    /**
     * Create an instance of {@link SimphonyPosApiCheckPrintResponse }
     * 
     */
    public SimphonyPosApiCheckPrintResponse createSimphonyPosApiCheckPrintResponse() {
        return new SimphonyPosApiCheckPrintResponse();
    }

    /**
     * Create an instance of {@link GetPrintedCheckResponse }
     * 
     */
    public GetPrintedCheckResponse createGetPrintedCheckResponse() {
        return new GetPrintedCheckResponse();
    }

    /**
     * Create an instance of {@link GetOpenChecks }
     * 
     */
    public GetOpenChecks createGetOpenChecks() {
        return new GetOpenChecks();
    }

    /**
     * Create an instance of {@link SimphonyPosApiOpenChecks }
     * 
     */
    public SimphonyPosApiOpenChecks createSimphonyPosApiOpenChecks() {
        return new SimphonyPosApiOpenChecks();
    }

    /**
     * Create an instance of {@link GetOpenChecksResponse }
     * 
     */
    public GetOpenChecksResponse createGetOpenChecksResponse() {
        return new GetOpenChecksResponse();
    }

    /**
     * Create an instance of {@link GetOpenChecksEx }
     * 
     */
    public GetOpenChecksEx createGetOpenChecksEx() {
        return new GetOpenChecksEx();
    }

    /**
     * Create an instance of {@link GetOpenChecksExResponse }
     * 
     */
    public GetOpenChecksExResponse createGetOpenChecksExResponse() {
        return new GetOpenChecksExResponse();
    }

    /**
     * Create an instance of {@link GetOpenChecksByRVC }
     * 
     */
    public GetOpenChecksByRVC createGetOpenChecksByRVC() {
        return new GetOpenChecksByRVC();
    }

    /**
     * Create an instance of {@link GetOpenChecksByRVCResponse }
     * 
     */
    public GetOpenChecksByRVCResponse createGetOpenChecksByRVCResponse() {
        return new GetOpenChecksByRVCResponse();
    }

    /**
     * Create an instance of {@link GetChecks }
     * 
     */
    public GetChecks createGetChecks() {
        return new GetChecks();
    }

    /**
     * Create an instance of {@link SimphonyPosApiCheckRequest }
     * 
     */
    public SimphonyPosApiCheckRequest createSimphonyPosApiCheckRequest() {
        return new SimphonyPosApiCheckRequest();
    }

    /**
     * Create an instance of {@link SimphonyPosApiCheckResponse }
     * 
     */
    public SimphonyPosApiCheckResponse createSimphonyPosApiCheckResponse() {
        return new SimphonyPosApiCheckResponse();
    }

    /**
     * Create an instance of {@link GetChecksResponse }
     * 
     */
    public GetChecksResponse createGetChecksResponse() {
        return new GetChecksResponse();
    }

    /**
     * Create an instance of {@link GetCheckDetail }
     * 
     */
    public GetCheckDetail createGetCheckDetail() {
        return new GetCheckDetail();
    }

    /**
     * Create an instance of {@link SimphonyPosApiCheckDetailRequest }
     * 
     */
    public SimphonyPosApiCheckDetailRequest createSimphonyPosApiCheckDetailRequest() {
        return new SimphonyPosApiCheckDetailRequest();
    }

    /**
     * Create an instance of {@link SimphonyPosApiCheckDetailResponse }
     * 
     */
    public SimphonyPosApiCheckDetailResponse createSimphonyPosApiCheckDetailResponse() {
        return new SimphonyPosApiCheckDetailResponse();
    }

    /**
     * Create an instance of {@link GetCheckDetailResponse }
     * 
     */
    public GetCheckDetailResponse createGetCheckDetailResponse() {
        return new GetCheckDetailResponse();
    }

    /**
     * Create an instance of {@link CalculateTransactionTotalsEx }
     * 
     */
    public CalculateTransactionTotalsEx createCalculateTransactionTotalsEx() {
        return new CalculateTransactionTotalsEx();
    }

    /**
     * Create an instance of {@link ArrayOfSimphonyPosApiMenuItemEx }
     * 
     */
    public ArrayOfSimphonyPosApiMenuItemEx createArrayOfSimphonyPosApiMenuItemEx() {
        return new ArrayOfSimphonyPosApiMenuItemEx();
    }

    /**
     * Create an instance of {@link ArrayOfSimphonyPosApiComboMealEx }
     * 
     */
    public ArrayOfSimphonyPosApiComboMealEx createArrayOfSimphonyPosApiComboMealEx() {
        return new ArrayOfSimphonyPosApiComboMealEx();
    }

    /**
     * Create an instance of {@link SimphonyPosApiSvcChargeEx }
     * 
     */
    public SimphonyPosApiSvcChargeEx createSimphonyPosApiSvcChargeEx() {
        return new SimphonyPosApiSvcChargeEx();
    }

    /**
     * Create an instance of {@link ArrayOfSimphonyPosApiDiscountEx }
     * 
     */
    public ArrayOfSimphonyPosApiDiscountEx createArrayOfSimphonyPosApiDiscountEx() {
        return new ArrayOfSimphonyPosApiDiscountEx();
    }

    /**
     * Create an instance of {@link SimphonyPosApiTotalsResponseEx }
     * 
     */
    public SimphonyPosApiTotalsResponseEx createSimphonyPosApiTotalsResponseEx() {
        return new SimphonyPosApiTotalsResponseEx();
    }

    /**
     * Create an instance of {@link CalculateTransactionTotalsExResponse }
     * 
     */
    public CalculateTransactionTotalsExResponse createCalculateTransactionTotalsExResponse() {
        return new CalculateTransactionTotalsExResponse();
    }

    /**
     * Create an instance of {@link PostTransactionEx2 }
     * 
     */
    public PostTransactionEx2 createPostTransactionEx2() {
        return new PostTransactionEx2();
    }

    /**
     * Create an instance of {@link ArrayOfSimphonyPosApiTmedDetailItemEx2 }
     * 
     */
    public ArrayOfSimphonyPosApiTmedDetailItemEx2 createArrayOfSimphonyPosApiTmedDetailItemEx2() {
        return new ArrayOfSimphonyPosApiTmedDetailItemEx2();
    }

    /**
     * Create an instance of {@link ArrayOfSimphonyPosApiExtensibility }
     * 
     */
    public ArrayOfSimphonyPosApiExtensibility createArrayOfSimphonyPosApiExtensibility() {
        return new ArrayOfSimphonyPosApiExtensibility();
    }

    /**
     * Create an instance of {@link PostTransactionEx2Response }
     * 
     */
    public PostTransactionEx2Response createPostTransactionEx2Response() {
        return new PostTransactionEx2Response();
    }

    /**
     * Create an instance of {@link AddToExistingCheckEx2 }
     * 
     */
    public AddToExistingCheckEx2 createAddToExistingCheckEx2() {
        return new AddToExistingCheckEx2();
    }

    /**
     * Create an instance of {@link SimphonyPosApiTmedDetailItemEx2 }
     * 
     */
    public SimphonyPosApiTmedDetailItemEx2 createSimphonyPosApiTmedDetailItemEx2() {
        return new SimphonyPosApiTmedDetailItemEx2();
    }

    /**
     * Create an instance of {@link AddToExistingCheckEx2Response }
     * 
     */
    public AddToExistingCheckEx2Response createAddToExistingCheckEx2Response() {
        return new AddToExistingCheckEx2Response();
    }

    /**
     * Create an instance of {@link SimphonyPosApiMenuItem }
     * 
     */
    public SimphonyPosApiMenuItem createSimphonyPosApiMenuItem() {
        return new SimphonyPosApiMenuItem();
    }

    /**
     * Create an instance of {@link ArrayOfSimphonyPosApiMenuItemDefinition }
     * 
     */
    public ArrayOfSimphonyPosApiMenuItemDefinition createArrayOfSimphonyPosApiMenuItemDefinition() {
        return new ArrayOfSimphonyPosApiMenuItemDefinition();
    }

    /**
     * Create an instance of {@link SimphonyPosApiMenuItemDefinition }
     * 
     */
    public SimphonyPosApiMenuItemDefinition createSimphonyPosApiMenuItemDefinition() {
        return new SimphonyPosApiMenuItemDefinition();
    }

    /**
     * Create an instance of {@link SimphonyPosApiComboMeal }
     * 
     */
    public SimphonyPosApiComboMeal createSimphonyPosApiComboMeal() {
        return new SimphonyPosApiComboMeal();
    }

    /**
     * Create an instance of {@link SimphonyPosApiOperationalResult }
     * 
     */
    public SimphonyPosApiOperationalResult createSimphonyPosApiOperationalResult() {
        return new SimphonyPosApiOperationalResult();
    }

    /**
     * Create an instance of {@link ArrayOfEConfigurationInfoType }
     * 
     */
    public ArrayOfEConfigurationInfoType createArrayOfEConfigurationInfoType() {
        return new ArrayOfEConfigurationInfoType();
    }

    /**
     * Create an instance of {@link ArrayOfSimphonyPosApiConfigInfo }
     * 
     */
    public ArrayOfSimphonyPosApiConfigInfo createArrayOfSimphonyPosApiConfigInfo() {
        return new ArrayOfSimphonyPosApiConfigInfo();
    }

    /**
     * Create an instance of {@link SimphonyPosApiConfigInfo }
     * 
     */
    public SimphonyPosApiConfigInfo createSimphonyPosApiConfigInfo() {
        return new SimphonyPosApiConfigInfo();
    }

    /**
     * Create an instance of {@link SimphonyPosApiEPayment }
     * 
     */
    public SimphonyPosApiEPayment createSimphonyPosApiEPayment() {
        return new SimphonyPosApiEPayment();
    }

    /**
     * Create an instance of {@link ArrayOfSimphonyPosApiCheckSummary }
     * 
     */
    public ArrayOfSimphonyPosApiCheckSummary createArrayOfSimphonyPosApiCheckSummary() {
        return new ArrayOfSimphonyPosApiCheckSummary();
    }

    /**
     * Create an instance of {@link SimphonyPosApiCheckSummary }
     * 
     */
    public SimphonyPosApiCheckSummary createSimphonyPosApiCheckSummary() {
        return new SimphonyPosApiCheckSummary();
    }

    /**
     * Create an instance of {@link ArrayOfSimphonyPosApiCheckSummaryEx }
     * 
     */
    public ArrayOfSimphonyPosApiCheckSummaryEx createArrayOfSimphonyPosApiCheckSummaryEx() {
        return new ArrayOfSimphonyPosApiCheckSummaryEx();
    }

    /**
     * Create an instance of {@link SimphonyPosApiCheckSummaryEx }
     * 
     */
    public SimphonyPosApiCheckSummaryEx createSimphonyPosApiCheckSummaryEx() {
        return new SimphonyPosApiCheckSummaryEx();
    }

    /**
     * Create an instance of {@link SimphonyPosApiKdsOrderStatus }
     * 
     */
    public SimphonyPosApiKdsOrderStatus createSimphonyPosApiKdsOrderStatus() {
        return new SimphonyPosApiKdsOrderStatus();
    }

    /**
     * Create an instance of {@link ArrayOfSimphonyPosApiKdsOrderStatus }
     * 
     */
    public ArrayOfSimphonyPosApiKdsOrderStatus createArrayOfSimphonyPosApiKdsOrderStatus() {
        return new ArrayOfSimphonyPosApiKdsOrderStatus();
    }

    /**
     * Create an instance of {@link SimphonyPosApiMenuItemEx }
     * 
     */
    public SimphonyPosApiMenuItemEx createSimphonyPosApiMenuItemEx() {
        return new SimphonyPosApiMenuItemEx();
    }

    /**
     * Create an instance of {@link SimphonyPosApiExtensibility }
     * 
     */
    public SimphonyPosApiExtensibility createSimphonyPosApiExtensibility() {
        return new SimphonyPosApiExtensibility();
    }

    /**
     * Create an instance of {@link ArrayOfSimphonyPosApiMenuItemDefinitionEx }
     * 
     */
    public ArrayOfSimphonyPosApiMenuItemDefinitionEx createArrayOfSimphonyPosApiMenuItemDefinitionEx() {
        return new ArrayOfSimphonyPosApiMenuItemDefinitionEx();
    }

    /**
     * Create an instance of {@link SimphonyPosApiMenuItemDefinitionEx }
     * 
     */
    public SimphonyPosApiMenuItemDefinitionEx createSimphonyPosApiMenuItemDefinitionEx() {
        return new SimphonyPosApiMenuItemDefinitionEx();
    }

    /**
     * Create an instance of {@link SimphonyPosApiDiscountEx }
     * 
     */
    public SimphonyPosApiDiscountEx createSimphonyPosApiDiscountEx() {
        return new SimphonyPosApiDiscountEx();
    }

    /**
     * Create an instance of {@link SimphonyPosApiComboMealEx }
     * 
     */
    public SimphonyPosApiComboMealEx createSimphonyPosApiComboMealEx() {
        return new SimphonyPosApiComboMealEx();
    }

    /**
     * Create an instance of {@link ArrayOfCheckTaxDataPerRate }
     * 
     */
    public ArrayOfCheckTaxDataPerRate createArrayOfCheckTaxDataPerRate() {
        return new ArrayOfCheckTaxDataPerRate();
    }

    /**
     * Create an instance of {@link CheckTaxDataPerRate }
     * 
     */
    public CheckTaxDataPerRate createCheckTaxDataPerRate() {
        return new CheckTaxDataPerRate();
    }

    /**
     * Create an instance of {@link SimphonyPosApiEPaymentEx }
     * 
     */
    public SimphonyPosApiEPaymentEx createSimphonyPosApiEPaymentEx() {
        return new SimphonyPosApiEPaymentEx();
    }

}
