//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://micros-hosting.com/EGateway/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
        ,xmlns = {@XmlNs(namespaceURI = "http://micros-hosting.com/EGateway/",prefix = "")})
package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlNs;