//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimphonyPosApi_TotalsResponseEx complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimphonyPosApi_TotalsResponseEx"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://micros-hosting.com/EGateway/}SimphonyPosApi_TotalsResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CheckTaxDataPerRate" type="{http://micros-hosting.com/EGateway/}ArrayOfCheckTaxDataPerRate" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimphonyPosApi_TotalsResponseEx", propOrder = {
    "checkTaxDataPerRate"
})
public class SimphonyPosApiTotalsResponseEx
    extends SimphonyPosApiTotalsResponse
{

    @XmlElement(name = "CheckTaxDataPerRate")
    protected ArrayOfCheckTaxDataPerRate checkTaxDataPerRate;

    /**
     * Gets the value of the checkTaxDataPerRate property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCheckTaxDataPerRate }
     *     
     */
    public ArrayOfCheckTaxDataPerRate getCheckTaxDataPerRate() {
        return checkTaxDataPerRate;
    }

    /**
     * Sets the value of the checkTaxDataPerRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCheckTaxDataPerRate }
     *     
     */
    public void setCheckTaxDataPerRate(ArrayOfCheckTaxDataPerRate value) {
        this.checkTaxDataPerRate = value;
    }

}
