//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimphonyPosApi_SvcCharge complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimphonyPosApi_SvcCharge"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SvcChgAmountOrPercent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SvcChgObjectNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="SvcChgReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimphonyPosApi_SvcCharge", propOrder = {
    "svcChgAmountOrPercent",
    "svcChgObjectNum",
    "svcChgReference"
})
public class SimphonyPosApiSvcCharge {

    @XmlElement(name = "SvcChgAmountOrPercent")
    protected String svcChgAmountOrPercent;
    @XmlElement(name = "SvcChgObjectNum")
    protected int svcChgObjectNum;
    @XmlElement(name = "SvcChgReference")
    protected String svcChgReference;

    /**
     * Gets the value of the svcChgAmountOrPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSvcChgAmountOrPercent() {
        return svcChgAmountOrPercent;
    }

    /**
     * Sets the value of the svcChgAmountOrPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSvcChgAmountOrPercent(String value) {
        this.svcChgAmountOrPercent = value;
    }

    /**
     * Gets the value of the svcChgObjectNum property.
     * 
     */
    public int getSvcChgObjectNum() {
        return svcChgObjectNum;
    }

    /**
     * Sets the value of the svcChgObjectNum property.
     * 
     */
    public void setSvcChgObjectNum(int value) {
        this.svcChgObjectNum = value;
    }

    /**
     * Gets the value of the svcChgReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSvcChgReference() {
        return svcChgReference;
    }

    /**
     * Sets the value of the svcChgReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSvcChgReference(String value) {
        this.svcChgReference = value;
    }

}
