//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimphonyPosApi_CheckPrintResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimphonyPosApi_CheckPrintResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OperationalResult" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_OperationalResult" minOccurs="0"/&gt;
 *         &lt;element name="CheckPrintLines" type="{http://micros-hosting.com/EGateway/}ArrayOfString" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimphonyPosApi_CheckPrintResponse", propOrder = {
    "operationalResult",
    "checkPrintLines"
})
public class SimphonyPosApiCheckPrintResponse {

    @XmlElement(name = "OperationalResult")
    protected SimphonyPosApiOperationalResult operationalResult;
    @XmlElement(name = "CheckPrintLines")
    protected ArrayOfString checkPrintLines;

    /**
     * Gets the value of the operationalResult property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiOperationalResult }
     *     
     */
    public SimphonyPosApiOperationalResult getOperationalResult() {
        return operationalResult;
    }

    /**
     * Sets the value of the operationalResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiOperationalResult }
     *     
     */
    public void setOperationalResult(SimphonyPosApiOperationalResult value) {
        this.operationalResult = value;
    }

    /**
     * Gets the value of the checkPrintLines property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getCheckPrintLines() {
        return checkPrintLines;
    }

    /**
     * Sets the value of the checkPrintLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setCheckPrintLines(ArrayOfString value) {
        this.checkPrintLines = value;
    }

}
