//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimphonyPrintApi_Status.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SimphonyPrintApi_Status"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="JobPending"/&gt;
 *     &lt;enumeration value="JobComplete"/&gt;
 *     &lt;enumeration value="JobAborted"/&gt;
 *     &lt;enumeration value="JobSentToBackup"/&gt;
 *     &lt;enumeration value="JobFailed"/&gt;
 *     &lt;enumeration value="JobNotFound"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SimphonyPrintApi_Status")
@XmlEnum
public enum SimphonyPrintApiStatus {

    @XmlEnumValue("JobPending")
    JOB_PENDING("JobPending"),
    @XmlEnumValue("JobComplete")
    JOB_COMPLETE("JobComplete"),
    @XmlEnumValue("JobAborted")
    JOB_ABORTED("JobAborted"),
    @XmlEnumValue("JobSentToBackup")
    JOB_SENT_TO_BACKUP("JobSentToBackup"),
    @XmlEnumValue("JobFailed")
    JOB_FAILED("JobFailed"),
    @XmlEnumValue("JobNotFound")
    JOB_NOT_FOUND("JobNotFound");
    private final String value;

    SimphonyPrintApiStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SimphonyPrintApiStatus fromValue(String v) {
        for (SimphonyPrintApiStatus c: SimphonyPrintApiStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
