//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimphonyPosApi_Extensibility complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimphonyPosApi_Extensibility"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DisplayName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExtensibilityAppName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExtensibilityDataName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExtensibilityDataType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PrintOptionBits" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StringData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DataID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimphonyPosApi_Extensibility", propOrder = {
    "displayName",
    "extensibilityAppName",
    "extensibilityDataName",
    "extensibilityDataType",
    "printOptionBits",
    "stringData",
    "dataID"
})
public class SimphonyPosApiExtensibility {

    @XmlElement(name = "DisplayName")
    protected String displayName;
    @XmlElement(name = "ExtensibilityAppName")
    protected String extensibilityAppName;
    @XmlElement(name = "ExtensibilityDataName")
    protected String extensibilityDataName;
    @XmlElement(name = "ExtensibilityDataType")
    protected String extensibilityDataType;
    @XmlElement(name = "PrintOptionBits")
    protected String printOptionBits;
    @XmlElement(name = "StringData")
    protected String stringData;
    @XmlElement(name = "DataID")
    protected String dataID;

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the extensibilityAppName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtensibilityAppName() {
        return extensibilityAppName;
    }

    /**
     * Sets the value of the extensibilityAppName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtensibilityAppName(String value) {
        this.extensibilityAppName = value;
    }

    /**
     * Gets the value of the extensibilityDataName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtensibilityDataName() {
        return extensibilityDataName;
    }

    /**
     * Sets the value of the extensibilityDataName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtensibilityDataName(String value) {
        this.extensibilityDataName = value;
    }

    /**
     * Gets the value of the extensibilityDataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtensibilityDataType() {
        return extensibilityDataType;
    }

    /**
     * Sets the value of the extensibilityDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtensibilityDataType(String value) {
        this.extensibilityDataType = value;
    }

    /**
     * Gets the value of the printOptionBits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintOptionBits() {
        return printOptionBits;
    }

    /**
     * Sets the value of the printOptionBits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintOptionBits(String value) {
        this.printOptionBits = value;
    }

    /**
     * Gets the value of the stringData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStringData() {
        return stringData;
    }

    /**
     * Sets the value of the stringData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStringData(String value) {
        this.stringData = value;
    }

    /**
     * Gets the value of the dataID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataID() {
        return dataID;
    }

    /**
     * Sets the value of the dataID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataID(String value) {
        this.dataID = value;
    }

}
