//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimphonyPosApi_CheckSummaryEx complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimphonyPosApi_CheckSummaryEx"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://micros-hosting.com/EGateway/}SimphonyPosApi_CheckSummary"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LastKnownKdsOrderStatus" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_KdsOrderStatus" minOccurs="0"/&gt;
 *         &lt;element name="KdsOrderStatusHistory" type="{http://micros-hosting.com/EGateway/}ArrayOfSimphonyPosApi_KdsOrderStatus" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimphonyPosApi_CheckSummaryEx", propOrder = {
    "lastKnownKdsOrderStatus",
    "kdsOrderStatusHistory"
})
public class SimphonyPosApiCheckSummaryEx
    extends SimphonyPosApiCheckSummary
{

    @XmlElement(name = "LastKnownKdsOrderStatus")
    protected SimphonyPosApiKdsOrderStatus lastKnownKdsOrderStatus;
    @XmlElement(name = "KdsOrderStatusHistory")
    protected ArrayOfSimphonyPosApiKdsOrderStatus kdsOrderStatusHistory;

    /**
     * Gets the value of the lastKnownKdsOrderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiKdsOrderStatus }
     *     
     */
    public SimphonyPosApiKdsOrderStatus getLastKnownKdsOrderStatus() {
        return lastKnownKdsOrderStatus;
    }

    /**
     * Sets the value of the lastKnownKdsOrderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiKdsOrderStatus }
     *     
     */
    public void setLastKnownKdsOrderStatus(SimphonyPosApiKdsOrderStatus value) {
        this.lastKnownKdsOrderStatus = value;
    }

    /**
     * Gets the value of the kdsOrderStatusHistory property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSimphonyPosApiKdsOrderStatus }
     *     
     */
    public ArrayOfSimphonyPosApiKdsOrderStatus getKdsOrderStatusHistory() {
        return kdsOrderStatusHistory;
    }

    /**
     * Sets the value of the kdsOrderStatusHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSimphonyPosApiKdsOrderStatus }
     *     
     */
    public void setKdsOrderStatusHistory(ArrayOfSimphonyPosApiKdsOrderStatus value) {
        this.kdsOrderStatusHistory = value;
    }

}
