//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimphonyPosApi_DiscountEx complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimphonyPosApi_DiscountEx"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Extensibility" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_Extensibility" minOccurs="0"/&gt;
 *         &lt;element name="DiscAmountOrPercent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DiscObjectNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="DiscReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimphonyPosApi_DiscountEx", propOrder = {
    "extensibility",
    "discAmountOrPercent",
    "discObjectNum",
    "discReference"
})
public class SimphonyPosApiDiscountEx {

    @XmlElement(name = "Extensibility")
    protected SimphonyPosApiExtensibility extensibility;
    @XmlElement(name = "DiscAmountOrPercent")
    protected String discAmountOrPercent;
    @XmlElement(name = "DiscObjectNum")
    protected int discObjectNum;
    @XmlElement(name = "DiscReference")
    protected String discReference;

    /**
     * Gets the value of the extensibility property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiExtensibility }
     *     
     */
    public SimphonyPosApiExtensibility getExtensibility() {
        return extensibility;
    }

    /**
     * Sets the value of the extensibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiExtensibility }
     *     
     */
    public void setExtensibility(SimphonyPosApiExtensibility value) {
        this.extensibility = value;
    }

    /**
     * Gets the value of the discAmountOrPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscAmountOrPercent() {
        return discAmountOrPercent;
    }

    /**
     * Sets the value of the discAmountOrPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscAmountOrPercent(String value) {
        this.discAmountOrPercent = value;
    }

    /**
     * Gets the value of the discObjectNum property.
     * 
     */
    public int getDiscObjectNum() {
        return discObjectNum;
    }

    /**
     * Sets the value of the discObjectNum property.
     * 
     */
    public void setDiscObjectNum(int value) {
        this.discObjectNum = value;
    }

    /**
     * Gets the value of the discReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscReference() {
        return discReference;
    }

    /**
     * Sets the value of the discReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscReference(String value) {
        this.discReference = value;
    }

}
