//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SimphonyPosApi_CheckRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimphonyPosApi_CheckRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VendorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CheckNumbers" type="{http://micros-hosting.com/EGateway/}ArrayOfInt" minOccurs="0"/&gt;
 *         &lt;element name="EmployeeObjectNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="RvcObjectNum" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="OrderTypeID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="KdsOrderStatus" type="{http://micros-hosting.com/EGateway/}ArrayOfInt" minOccurs="0"/&gt;
 *         &lt;element name="LookUpStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="IncludeClosedCheck" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimphonyPosApi_CheckRequest", propOrder = {
    "vendorCode",
    "checkNumbers",
    "employeeObjectNum",
    "rvcObjectNum",
    "orderTypeID",
    "kdsOrderStatus",
    "lookUpStartDate",
    "includeClosedCheck"
})
public class SimphonyPosApiCheckRequest {

    @XmlElement(name = "VendorCode")
    protected String vendorCode;
    @XmlElement(name = "CheckNumbers")
    protected ArrayOfInt checkNumbers;
    @XmlElement(name = "EmployeeObjectNum")
    protected int employeeObjectNum;
    @XmlElement(name = "RvcObjectNum")
    protected int rvcObjectNum;
    @XmlElement(name = "OrderTypeID")
    protected int orderTypeID;
    @XmlElement(name = "KdsOrderStatus")
    protected ArrayOfInt kdsOrderStatus;
    @XmlElement(name = "LookUpStartDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lookUpStartDate;
    @XmlElement(name = "IncludeClosedCheck")
    protected boolean includeClosedCheck;

    /**
     * Gets the value of the vendorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorCode() {
        return vendorCode;
    }

    /**
     * Sets the value of the vendorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorCode(String value) {
        this.vendorCode = value;
    }

    /**
     * Gets the value of the checkNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfInt }
     *     
     */
    public ArrayOfInt getCheckNumbers() {
        return checkNumbers;
    }

    /**
     * Sets the value of the checkNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfInt }
     *     
     */
    public void setCheckNumbers(ArrayOfInt value) {
        this.checkNumbers = value;
    }

    /**
     * Gets the value of the employeeObjectNum property.
     * 
     */
    public int getEmployeeObjectNum() {
        return employeeObjectNum;
    }

    /**
     * Sets the value of the employeeObjectNum property.
     * 
     */
    public void setEmployeeObjectNum(int value) {
        this.employeeObjectNum = value;
    }

    /**
     * Gets the value of the rvcObjectNum property.
     * 
     */
    public int getRvcObjectNum() {
        return rvcObjectNum;
    }

    /**
     * Sets the value of the rvcObjectNum property.
     * 
     */
    public void setRvcObjectNum(int value) {
        this.rvcObjectNum = value;
    }

    /**
     * Gets the value of the orderTypeID property.
     * 
     */
    public int getOrderTypeID() {
        return orderTypeID;
    }

    /**
     * Sets the value of the orderTypeID property.
     * 
     */
    public void setOrderTypeID(int value) {
        this.orderTypeID = value;
    }

    /**
     * Gets the value of the kdsOrderStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfInt }
     *     
     */
    public ArrayOfInt getKdsOrderStatus() {
        return kdsOrderStatus;
    }

    /**
     * Sets the value of the kdsOrderStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfInt }
     *     
     */
    public void setKdsOrderStatus(ArrayOfInt value) {
        this.kdsOrderStatus = value;
    }

    /**
     * Gets the value of the lookUpStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLookUpStartDate() {
        return lookUpStartDate;
    }

    /**
     * Sets the value of the lookUpStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLookUpStartDate(XMLGregorianCalendar value) {
        this.lookUpStartDate = value;
    }

    /**
     * Gets the value of the includeClosedCheck property.
     * 
     */
    public boolean isIncludeClosedCheck() {
        return includeClosedCheck;
    }

    /**
     * Sets the value of the includeClosedCheck property.
     * 
     */
    public void setIncludeClosedCheck(boolean value) {
        this.includeClosedCheck = value;
    }

}
