//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimphonyPrintApi_PrintJobStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimphonyPrintApi_PrintJobStatus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Status" type="{http://micros-hosting.com/EGateway/}SimphonyPrintApi_Status"/&gt;
 *         &lt;element name="PrintJobList" type="{http://micros-hosting.com/EGateway/}ArrayOfInt" minOccurs="0"/&gt;
 *         &lt;element name="OperationalResult" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_OperationalResult" minOccurs="0"/&gt;
 *         &lt;element name="StatusMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SystemStatusMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimphonyPrintApi_PrintJobStatus", propOrder = {
    "status",
    "printJobList",
    "operationalResult",
    "statusMsg",
    "systemStatusMsg"
})
public class SimphonyPrintApiPrintJobStatus {

    @XmlElement(name = "Status", required = true)
    @XmlSchemaType(name = "string")
    protected SimphonyPrintApiStatus status;
    @XmlElement(name = "PrintJobList")
    protected ArrayOfInt printJobList;
    @XmlElement(name = "OperationalResult")
    protected SimphonyPosApiOperationalResult operationalResult;
    @XmlElement(name = "StatusMsg")
    protected String statusMsg;
    @XmlElement(name = "SystemStatusMsg")
    protected String systemStatusMsg;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPrintApiStatus }
     *     
     */
    public SimphonyPrintApiStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPrintApiStatus }
     *     
     */
    public void setStatus(SimphonyPrintApiStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the printJobList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfInt }
     *     
     */
    public ArrayOfInt getPrintJobList() {
        return printJobList;
    }

    /**
     * Sets the value of the printJobList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfInt }
     *     
     */
    public void setPrintJobList(ArrayOfInt value) {
        this.printJobList = value;
    }

    /**
     * Gets the value of the operationalResult property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiOperationalResult }
     *     
     */
    public SimphonyPosApiOperationalResult getOperationalResult() {
        return operationalResult;
    }

    /**
     * Sets the value of the operationalResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiOperationalResult }
     *     
     */
    public void setOperationalResult(SimphonyPosApiOperationalResult value) {
        this.operationalResult = value;
    }

    /**
     * Gets the value of the statusMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusMsg() {
        return statusMsg;
    }

    /**
     * Sets the value of the statusMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusMsg(String value) {
        this.statusMsg = value;
    }

    /**
     * Gets the value of the systemStatusMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemStatusMsg() {
        return systemStatusMsg;
    }

    /**
     * Sets the value of the systemStatusMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemStatusMsg(String value) {
        this.systemStatusMsg = value;
    }

}
