//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimphonyPosApi_TotalsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimphonyPosApi_TotalsResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OperationalResult" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_OperationalResult" minOccurs="0"/&gt;
 *         &lt;element name="TotalsAutoSvcChgTotals" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TotalsOtherTotals" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TotalsSubTotal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TotalsTaxTotals" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TotalsTotalDue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimphonyPosApi_TotalsResponse", propOrder = {
    "operationalResult",
    "totalsAutoSvcChgTotals",
    "totalsOtherTotals",
    "totalsSubTotal",
    "totalsTaxTotals",
    "totalsTotalDue"
})
@XmlSeeAlso({
    SimphonyPosApiTotalsResponseEx.class
})
public class SimphonyPosApiTotalsResponse {

    @XmlElement(name = "OperationalResult")
    protected SimphonyPosApiOperationalResult operationalResult;
    @XmlElement(name = "TotalsAutoSvcChgTotals")
    protected String totalsAutoSvcChgTotals;
    @XmlElement(name = "TotalsOtherTotals")
    protected String totalsOtherTotals;
    @XmlElement(name = "TotalsSubTotal")
    protected String totalsSubTotal;
    @XmlElement(name = "TotalsTaxTotals")
    protected String totalsTaxTotals;
    @XmlElement(name = "TotalsTotalDue")
    protected String totalsTotalDue;

    /**
     * Gets the value of the operationalResult property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiOperationalResult }
     *     
     */
    public SimphonyPosApiOperationalResult getOperationalResult() {
        return operationalResult;
    }

    /**
     * Sets the value of the operationalResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiOperationalResult }
     *     
     */
    public void setOperationalResult(SimphonyPosApiOperationalResult value) {
        this.operationalResult = value;
    }

    /**
     * Gets the value of the totalsAutoSvcChgTotals property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalsAutoSvcChgTotals() {
        return totalsAutoSvcChgTotals;
    }

    /**
     * Sets the value of the totalsAutoSvcChgTotals property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalsAutoSvcChgTotals(String value) {
        this.totalsAutoSvcChgTotals = value;
    }

    /**
     * Gets the value of the totalsOtherTotals property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalsOtherTotals() {
        return totalsOtherTotals;
    }

    /**
     * Sets the value of the totalsOtherTotals property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalsOtherTotals(String value) {
        this.totalsOtherTotals = value;
    }

    /**
     * Gets the value of the totalsSubTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalsSubTotal() {
        return totalsSubTotal;
    }

    /**
     * Sets the value of the totalsSubTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalsSubTotal(String value) {
        this.totalsSubTotal = value;
    }

    /**
     * Gets the value of the totalsTaxTotals property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalsTaxTotals() {
        return totalsTaxTotals;
    }

    /**
     * Sets the value of the totalsTaxTotals property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalsTaxTotals(String value) {
        this.totalsTaxTotals = value;
    }

    /**
     * Gets the value of the totalsTotalDue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalsTotalDue() {
        return totalsTotalDue;
    }

    /**
     * Sets the value of the totalsTotalDue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalsTotalDue(String value) {
        this.totalsTotalDue = value;
    }

}
