//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.23 at 02:11:47 AM IST 
//


package com.simphony.pos.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SimphonyPosApi_ConfigInfoResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimphonyPosApi_ConfigInfoResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OperationalResult" type="{http://micros-hosting.com/EGateway/}SimphonyPosApi_OperationalResult" minOccurs="0"/&gt;
 *         &lt;element name="ConfigInfoType" type="{http://micros-hosting.com/EGateway/}ArrayOfEConfigurationInfoType" minOccurs="0"/&gt;
 *         &lt;element name="LanguageInformation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ServingPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ServiceCharge" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MenuLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TenderMedia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Tables" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RevenueCenters" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RevenueCenterParameter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OrderType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MajorGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MenuItemClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MenuItemPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Employees" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Discounts" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MenuItemDefinitions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FamilyGroups" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Interfaces" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MenuItemMasters" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MenuItemSlu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MainMenuLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SubMenuLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EventTypes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EventSubTypes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EventDefinitions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Tax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimphonyPosApi_ConfigInfoResponse", propOrder = {
    "operationalResult",
    "configInfoType",
    "languageInformation",
    "servingPeriod",
    "serviceCharge",
    "version",
    "menuLevel",
    "tenderMedia",
    "tables",
    "revenueCenters",
    "revenueCenterParameter",
    "orderType",
    "majorGroup",
    "menuItemClass",
    "menuItemPrice",
    "employees",
    "discounts",
    "currency",
    "menuItemDefinitions",
    "familyGroups",
    "interfaces",
    "menuItemMasters",
    "menuItemSlu",
    "mainMenuLevel",
    "subMenuLevel",
    "eventTypes",
    "eventSubTypes",
    "eventDefinitions",
    "tax"
})
public class SimphonyPosApiConfigInfoResponse {

    @XmlElement(name = "OperationalResult")
    protected SimphonyPosApiOperationalResult operationalResult;
    @XmlElement(name = "ConfigInfoType")
    protected ArrayOfEConfigurationInfoType configInfoType;
    @XmlElement(name = "LanguageInformation")
    protected String languageInformation;
    @XmlElement(name = "ServingPeriod")
    protected String servingPeriod;
    @XmlElement(name = "ServiceCharge")
    protected String serviceCharge;
    @XmlElement(name = "Version")
    protected String version;
    @XmlElement(name = "MenuLevel")
    protected String menuLevel;
    @XmlElement(name = "TenderMedia")
    protected String tenderMedia;
    @XmlElement(name = "Tables")
    protected String tables;
    @XmlElement(name = "RevenueCenters")
    protected String revenueCenters;
    @XmlElement(name = "RevenueCenterParameter")
    protected String revenueCenterParameter;
    @XmlElement(name = "OrderType")
    protected String orderType;
    @XmlElement(name = "MajorGroup")
    protected String majorGroup;
    @XmlElement(name = "MenuItemClass")
    protected String menuItemClass;
    @XmlElement(name = "MenuItemPrice")
    protected String menuItemPrice;
    @XmlElement(name = "Employees")
    protected String employees;
    @XmlElement(name = "Discounts")
    protected String discounts;
    @XmlElement(name = "Currency")
    protected String currency;
    @XmlElement(name = "MenuItemDefinitions")
    protected String menuItemDefinitions;
    @XmlElement(name = "FamilyGroups")
    protected String familyGroups;
    @XmlElement(name = "Interfaces")
    protected String interfaces;
    @XmlElement(name = "MenuItemMasters")
    protected String menuItemMasters;
    @XmlElement(name = "MenuItemSlu")
    protected String menuItemSlu;
    @XmlElement(name = "MainMenuLevel")
    protected String mainMenuLevel;
    @XmlElement(name = "SubMenuLevel")
    protected String subMenuLevel;
    @XmlElement(name = "EventTypes")
    protected String eventTypes;
    @XmlElement(name = "EventSubTypes")
    protected String eventSubTypes;
    @XmlElement(name = "EventDefinitions")
    protected String eventDefinitions;
    @XmlElement(name = "Tax")
    protected String tax;

    /**
     * Gets the value of the operationalResult property.
     * 
     * @return
     *     possible object is
     *     {@link SimphonyPosApiOperationalResult }
     *     
     */
    public SimphonyPosApiOperationalResult getOperationalResult() {
        return operationalResult;
    }

    /**
     * Sets the value of the operationalResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimphonyPosApiOperationalResult }
     *     
     */
    public void setOperationalResult(SimphonyPosApiOperationalResult value) {
        this.operationalResult = value;
    }

    /**
     * Gets the value of the configInfoType property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfEConfigurationInfoType }
     *     
     */
    public ArrayOfEConfigurationInfoType getConfigInfoType() {
        return configInfoType;
    }

    /**
     * Sets the value of the configInfoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfEConfigurationInfoType }
     *     
     */
    public void setConfigInfoType(ArrayOfEConfigurationInfoType value) {
        this.configInfoType = value;
    }

    /**
     * Gets the value of the languageInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageInformation() {
        return languageInformation;
    }

    /**
     * Sets the value of the languageInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageInformation(String value) {
        this.languageInformation = value;
    }

    /**
     * Gets the value of the servingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServingPeriod() {
        return servingPeriod;
    }

    /**
     * Sets the value of the servingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServingPeriod(String value) {
        this.servingPeriod = value;
    }

    /**
     * Gets the value of the serviceCharge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCharge() {
        return serviceCharge;
    }

    /**
     * Sets the value of the serviceCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCharge(String value) {
        this.serviceCharge = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the menuLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenuLevel() {
        return menuLevel;
    }

    /**
     * Sets the value of the menuLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenuLevel(String value) {
        this.menuLevel = value;
    }

    /**
     * Gets the value of the tenderMedia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenderMedia() {
        return tenderMedia;
    }

    /**
     * Sets the value of the tenderMedia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenderMedia(String value) {
        this.tenderMedia = value;
    }

    /**
     * Gets the value of the tables property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTables() {
        return tables;
    }

    /**
     * Sets the value of the tables property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTables(String value) {
        this.tables = value;
    }

    /**
     * Gets the value of the revenueCenters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevenueCenters() {
        return revenueCenters;
    }

    /**
     * Sets the value of the revenueCenters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevenueCenters(String value) {
        this.revenueCenters = value;
    }

    /**
     * Gets the value of the revenueCenterParameter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevenueCenterParameter() {
        return revenueCenterParameter;
    }

    /**
     * Sets the value of the revenueCenterParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevenueCenterParameter(String value) {
        this.revenueCenterParameter = value;
    }

    /**
     * Gets the value of the orderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the majorGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMajorGroup() {
        return majorGroup;
    }

    /**
     * Sets the value of the majorGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMajorGroup(String value) {
        this.majorGroup = value;
    }

    /**
     * Gets the value of the menuItemClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenuItemClass() {
        return menuItemClass;
    }

    /**
     * Sets the value of the menuItemClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenuItemClass(String value) {
        this.menuItemClass = value;
    }

    /**
     * Gets the value of the menuItemPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenuItemPrice() {
        return menuItemPrice;
    }

    /**
     * Sets the value of the menuItemPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenuItemPrice(String value) {
        this.menuItemPrice = value;
    }

    /**
     * Gets the value of the employees property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployees() {
        return employees;
    }

    /**
     * Sets the value of the employees property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployees(String value) {
        this.employees = value;
    }

    /**
     * Gets the value of the discounts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscounts() {
        return discounts;
    }

    /**
     * Sets the value of the discounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscounts(String value) {
        this.discounts = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the menuItemDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenuItemDefinitions() {
        return menuItemDefinitions;
    }

    /**
     * Sets the value of the menuItemDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenuItemDefinitions(String value) {
        this.menuItemDefinitions = value;
    }

    /**
     * Gets the value of the familyGroups property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilyGroups() {
        return familyGroups;
    }

    /**
     * Sets the value of the familyGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilyGroups(String value) {
        this.familyGroups = value;
    }

    /**
     * Gets the value of the interfaces property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaces() {
        return interfaces;
    }

    /**
     * Sets the value of the interfaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaces(String value) {
        this.interfaces = value;
    }

    /**
     * Gets the value of the menuItemMasters property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenuItemMasters() {
        return menuItemMasters;
    }

    /**
     * Sets the value of the menuItemMasters property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenuItemMasters(String value) {
        this.menuItemMasters = value;
    }

    /**
     * Gets the value of the menuItemSlu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenuItemSlu() {
        return menuItemSlu;
    }

    /**
     * Sets the value of the menuItemSlu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenuItemSlu(String value) {
        this.menuItemSlu = value;
    }

    /**
     * Gets the value of the mainMenuLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainMenuLevel() {
        return mainMenuLevel;
    }

    /**
     * Sets the value of the mainMenuLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainMenuLevel(String value) {
        this.mainMenuLevel = value;
    }

    /**
     * Gets the value of the subMenuLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubMenuLevel() {
        return subMenuLevel;
    }

    /**
     * Sets the value of the subMenuLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubMenuLevel(String value) {
        this.subMenuLevel = value;
    }

    /**
     * Gets the value of the eventTypes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventTypes() {
        return eventTypes;
    }

    /**
     * Sets the value of the eventTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventTypes(String value) {
        this.eventTypes = value;
    }

    /**
     * Gets the value of the eventSubTypes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventSubTypes() {
        return eventSubTypes;
    }

    /**
     * Sets the value of the eventSubTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventSubTypes(String value) {
        this.eventSubTypes = value;
    }

    /**
     * Gets the value of the eventDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventDefinitions() {
        return eventDefinitions;
    }

    /**
     * Sets the value of the eventDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventDefinitions(String value) {
        this.eventDefinitions = value;
    }

    /**
     * Gets the value of the tax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTax() {
        return tax;
    }

    /**
     * Sets the value of the tax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTax(String value) {
        this.tax = value;
    }

}
